import type {
    SEOAnalysisResult,
    SEORecommendation,
    SEORecommendationSeverity,
} from "@/lib/validations/seo";

/* -------------------------------------------------------------------------- */
/* Types                                                                      */
/* -------------------------------------------------------------------------- */

export type SEOScoreStatus =
    | "EXCELLENT"
    | "GOOD"
    | "NEEDS_IMPROVEMENT"
    | "POOR";

export interface SEOAnalysisSummary {
    score: number;
    status: SEOScoreStatus;
    criticalCount: number;
    warningCount: number;
    successCount: number;
    totalRecommendations: number;
}

export interface SEORecommendationGroups {
    critical: SEORecommendation[];
    warning: SEORecommendation[];
    success: SEORecommendation[];
}

/* -------------------------------------------------------------------------- */
/* Text Utilities                                                             */
/* -------------------------------------------------------------------------- */

/**
 * Converts HTML content into readable plain text.
 *
 * This utility is intentionally lightweight and does not attempt to behave
 * like a full browser HTML parser. It is suitable for SEO/editor content
 * generated by the application.
 */
export function stripHtml(value: string): string {
    if (!value) {
        return "";
    }

    return value
        .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, " ")
        .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, " ")
        .replace(/<[^>]*>/g, " ")
        .replace(/&nbsp;/gi, " ")
        .replace(/&amp;/gi, "&")
        .replace(/&lt;/gi, "<")
        .replace(/&gt;/gi, ">")
        .replace(/&quot;/gi, '"')
        .replace(/&#39;|&apos;/gi, "'")
        .replace(/\s+/g, " ")
        .trim();
}

/**
 * Normalizes arbitrary text for word-count and content analysis utilities.
 */
export function normalizeText(value: string): string {
    return stripHtml(value);
}

/**
 * Counts words in plain text or HTML content.
 */
export function countWords(value: string): number {
    const text = normalizeText(value);

    if (!text) {
        return 0;
    }

    return text
        .split(/\s+/)
        .map((word) => word.trim())
        .filter(Boolean)
        .length;
}

/* -------------------------------------------------------------------------- */
/* Reading Time                                                               */
/* -------------------------------------------------------------------------- */

/**
 * Calculates estimated reading time in minutes.
 *
 * Uses 200 words per minute as a practical default for general web content.
 */
export function calculateReadingTime(
    content: string,
    wordsPerMinute = 200,
): number {
    const wordCount = countWords(content);

    if (wordCount === 0) {
        return 1;
    }

    const safeWordsPerMinute =
        Number.isFinite(wordsPerMinute) && wordsPerMinute > 0
            ? wordsPerMinute
            : 200;

    return Math.max(
        1,
        Math.ceil(wordCount / safeWordsPerMinute),
    );
}

/* -------------------------------------------------------------------------- */
/* Recommendation Utilities                                                   */
/* -------------------------------------------------------------------------- */

/**
 * Returns recommendations matching a specific severity.
 */
export function getRecommendationsBySeverity(
    recommendations: SEORecommendation[],
    severity: SEORecommendationSeverity,
): SEORecommendation[] {
    return recommendations.filter(
        (recommendation) => recommendation.severity === severity,
    );
}

/**
 * Groups recommendations by severity.
 */
export function groupRecommendations(
    recommendations: SEORecommendation[],
): SEORecommendationGroups {
    return {
        critical: getRecommendationsBySeverity(
            recommendations,
            "CRITICAL",
        ),
        warning: getRecommendationsBySeverity(
            recommendations,
            "WARNING",
        ),
        success: getRecommendationsBySeverity(
            recommendations,
            "SUCCESS",
        ),
    };
}

/**
 * Returns the number of critical recommendations.
 */
export function countCriticalRecommendations(
    recommendations: SEORecommendation[],
): number {
    return recommendations.filter(
        (recommendation) => recommendation.severity === "CRITICAL",
    ).length;
}

/**
 * Returns the number of warning recommendations.
 */
export function countWarningRecommendations(
    recommendations: SEORecommendation[],
): number {
    return recommendations.filter(
        (recommendation) => recommendation.severity === "WARNING",
    ).length;
}

/**
 * Returns the number of successful recommendations.
 */
export function countSuccessRecommendations(
    recommendations: SEORecommendation[],
): number {
    return recommendations.filter(
        (recommendation) => recommendation.severity === "SUCCESS",
    ).length;
}

/**
 * Returns true when the analysis contains at least one critical issue.
 */
export function hasCriticalSEOIssues(
    recommendations: SEORecommendation[],
): boolean {
    return recommendations.some(
        (recommendation) => recommendation.severity === "CRITICAL",
    );
}

/* -------------------------------------------------------------------------- */
/* Score Utilities                                                            */
/* -------------------------------------------------------------------------- */

/**
 * Converts an SEO score into a stable status used by UI/API consumers.
 */
export function getSEOScoreStatus(
    score: number,
): SEOScoreStatus {
    const normalizedScore = Math.max(
        0,
        Math.min(100, Math.round(score)),
    );

    if (normalizedScore >= 90) {
        return "EXCELLENT";
    }

    if (normalizedScore >= 70) {
        return "GOOD";
    }

    if (normalizedScore >= 50) {
        return "NEEDS_IMPROVEMENT";
    }

    return "POOR";
}

/**
 * Returns a human-readable label for an SEO score status.
 */
export function getSEOScoreStatusLabel(
    status: SEOScoreStatus,
): string {
    switch (status) {
        case "EXCELLENT":
            return "Excellent";

        case "GOOD":
            return "Good";

        case "NEEDS_IMPROVEMENT":
            return "Needs Improvement";

        case "POOR":
            return "Poor";

        default:
            return "Needs Improvement";
    }
}

/**
 * Creates a complete summary from an SEO analysis result.
 */
export function summarizeSEOAnalysis(
    result: SEOAnalysisResult,
): SEOAnalysisSummary {
    const criticalCount = countCriticalRecommendations(
        result.recommendations,
    );

    const warningCount = countWarningRecommendations(
        result.recommendations,
    );

    const successCount = countSuccessRecommendations(
        result.recommendations,
    );

    const score = Math.max(
        0,
        Math.min(100, Math.round(result.score)),
    );

    return {
        score,
        status: getSEOScoreStatus(score),
        criticalCount,
        warningCount,
        successCount,
        totalRecommendations:
            result.recommendations.length,
    };
}

/* -------------------------------------------------------------------------- */
/* Recommendation Prioritization                                               */
/* -------------------------------------------------------------------------- */

/**
 * Sorts recommendations by importance.
 *
 * Critical issues are shown first, followed by warnings and successful
 * checks. Original ordering within the same severity is preserved.
 */
export function sortRecommendations(
    recommendations: SEORecommendation[],
): SEORecommendation[] {
    const severityWeight: Record<
        SEORecommendationSeverity,
        number
    > = {
        CRITICAL: 0,
        WARNING: 1,
        SUCCESS: 2,
    };

    return recommendations
        .map((recommendation, index) => ({
            recommendation,
            index,
        }))
        .sort((a, b) => {
            const severityDifference =
                severityWeight[a.recommendation.severity] -
                severityWeight[b.recommendation.severity];

            if (severityDifference !== 0) {
                return severityDifference;
            }

            return a.index - b.index;
        })
        .map(({ recommendation }) => recommendation);
}

/**
 * Returns only actionable SEO recommendations.
 *
 * Successful checks are excluded because they do not require corrective
 * action.
 */
export function getActionableRecommendations(
    recommendations: SEORecommendation[],
): SEORecommendation[] {
    return sortRecommendations(
        recommendations.filter(
            (recommendation) =>
                recommendation.severity !== "SUCCESS",
        ),
    );
}

/* -------------------------------------------------------------------------- */
/* Analysis Result Utilities                                                   */
/* -------------------------------------------------------------------------- */

/**
 * Normalizes an analysis score to the valid 0–100 range.
 */
export function normalizeSEOScore(score: number): number {
    if (!Number.isFinite(score)) {
        return 0;
    }

    return Math.max(
        0,
        Math.min(100, Math.round(score)),
    );
}

/**
 * Returns a normalized copy of an SEO analysis result.
 *
 * This prevents invalid scores from propagating into UI components.
 */
export function normalizeSEOAnalysisResult(
    result: SEOAnalysisResult,
): SEOAnalysisResult {
    return {
        score: normalizeSEOScore(result.score),
        recommendations: [...result.recommendations],
    };
}

/**
 * Returns true when an SEO analysis is considered healthy.
 *
 * A healthy result requires:
 * - a score of at least 70
 * - no critical recommendations
 */
export function isSEOAnalysisHealthy(
    result: SEOAnalysisResult,
): boolean {
    return (
        normalizeSEOScore(result.score) >= 70 &&
        !hasCriticalSEOIssues(result.recommendations)
    );
}

/**
 * Returns the highest-severity issue present in an analysis.
 */
export function getHighestRecommendationSeverity(
    recommendations: SEORecommendation[],
): SEORecommendationSeverity | null {
    if (
        recommendations.some(
            (recommendation) =>
                recommendation.severity === "CRITICAL",
        )
    ) {
        return "CRITICAL";
    }

    if (
        recommendations.some(
            (recommendation) =>
                recommendation.severity === "WARNING",
        )
    ) {
        return "WARNING";
    }

    if (
        recommendations.some(
            (recommendation) =>
                recommendation.severity === "SUCCESS",
        )
    ) {
        return "SUCCESS";
    }

    return null;
}